# Generated by Django 3.1.1 on 2020-11-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sgc_global_id', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('library', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundInPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_1536', models.CharField(max_length=4)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.compounds')),
                ('library_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.libraryplate')),
            ],
        ),
    ]
