# Generated by Django 3.1.1 on 2020-11-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(max_length=24)),
            ],
        ),
        migrations.RenameField(
            model_name='compoundinplate',
            old_name='location_1536',
            new_name='well',
        ),
        migrations.AlterField(
            model_name='compoundinplate',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.compound'),
        ),
        migrations.DeleteModel(
            name='Compounds',
        ),
    ]
