# Generated by Django 3.1.1 on 2020-11-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20201126_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('for_industry', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='compoundinplate',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='playground.compound'),
        ),
        migrations.AlterField(
            model_name='compoundinplate',
            name='library_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='playground.libraryplate'),
        ),
    ]
