# Generated by Django 3.1.1 on 2020-11-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_auto_20201130_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='library',
            field=models.CharField(max_length=100),
        ),
    ]
