# Generated by Django 3.1.1 on 2020-12-04 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20201130_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundinplate',
            name='concentration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='proposal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='libraryplate',
            name='concentration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryplate',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libraryplate',
            name='last_tested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LibrarySubset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proposal', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=64)),
                ('compounds', models.ManyToManyField(to='playground.CompoundInPlate')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.library')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proposal', models.CharField(blank=True, max_length=100, null=True)),
                ('plates', models.ManyToManyField(to='playground.LibraryPlate')),
                ('subsets', models.ManyToManyField(to='playground.LibrarySubset')),
            ],
        ),
    ]
