# Generated by Django 3.1.1 on 2020-12-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_auto_20201204_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompoundInPlate',
            new_name='SourceWell',
        ),
    ]
