# Generated by Django 3.1.1 on 2020-12-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_auto_20201204_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='proposal',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
