# Generated by Django 3.1.1 on 2020-12-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_auto_20201207_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryplate',
            name='concentration',
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='last_tested',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sourcewell',
            name='concentration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
