# Generated by Django 3.1.1 on 2020-12-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_auto_20201207_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundselection',
            name='plates',
            field=models.ManyToManyField(blank=True, to='playground.LibraryPlate'),
        ),
        migrations.AlterField(
            model_name='compoundselection',
            name='subsets',
            field=models.ManyToManyField(blank=True, to='playground.LibrarySubset'),
        ),
    ]
