# Generated by Django 3.1.1 on 2020-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_auto_20201208_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('space_group', models.CharField(max_length=100)),
                ('a', models.DecimalField(decimal_places=2, max_digits=10)),
                ('b', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gamma', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
