# Generated by Django 3.1.1 on 2021-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_auto_20201209_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(max_length=64)),
                ('library_plate', models.CharField(max_length=64)),
                ('source_well', models.CharField(max_length=4)),
                ('compound_code', models.CharField(max_length=64)),
                ('smiles', models.CharField(max_length=128)),
                ('concentration', models.IntegerField()),
            ],
        ),
    ]
