# Generated by Django 3.1.5 on 2021-01-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='compoundselection',
            name='plates',
        ),
        migrations.AddField(
            model_name='compoundselection',
            name='libraries',
            field=models.ManyToManyField(blank=True, to='playground.Library'),
        ),
        migrations.AddField(
            model_name='librarysubset',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.preset'),
        ),
    ]
