# Generated by Django 3.1.5 on 2021-01-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_auto_20210125_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoundselection',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='compoundselection',
            name='subsets',
        ),
        migrations.RemoveField(
            model_name='libraryplate',
            name='library',
        ),
        migrations.RemoveField(
            model_name='librarysubset',
            name='compounds',
        ),
        migrations.RemoveField(
            model_name='librarysubset',
            name='library',
        ),
        migrations.RemoveField(
            model_name='librarysubset',
            name='preset',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.RemoveField(
            model_name='sourcewell',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='sourcewell',
            name='library_plate',
        ),
        migrations.DeleteModel(
            name='Compound',
        ),
        migrations.DeleteModel(
            name='CompoundSelection',
        ),
        migrations.DeleteModel(
            name='LibraryPlate',
        ),
        migrations.DeleteModel(
            name='LibrarySubset',
        ),
        migrations.DeleteModel(
            name='Preset',
        ),
        migrations.DeleteModel(
            name='SourceWell',
        ),
    ]
