# Generated by Django 3.1.5 on 2021-01-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0019_proposal_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='playground.proposal'),
        ),
    ]
