# Generated by Django 3.1.5 on 2021-01-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0020_auto_20210125_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='protein',
        ),
    ]
