# Generated by Django 3.1.5 on 2021-01-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0021_remove_proposal_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='industry_user',
            field=models.BooleanField(default=True),
        ),
    ]
