# Generated by Django 3.1.5 on 2021-01-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0022_proposal_industry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current', models.BooleanField(default=True)),
                ('last_tested', models.DateField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plates', to='playground.library')),
            ],
        ),
    ]
