# Generated by Django 3.1.5 on 2021-01-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0023_libraryplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='last_tested',
            field=models.DateField(auto_now=True),
        ),
    ]
