# Generated by Django 3.1.5 on 2021-01-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0024_auto_20210125_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=32)),
            ],
        ),
    ]
