# Generated by Django 3.1.5 on 2021-01-26 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0026_sourcewell'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySubset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=64)),
                ('compounds', models.ManyToManyField(to='playground.SourceWell')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.library')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='playground.proposal')),
            ],
        ),
    ]
