# Generated by Django 3.1.5 on 2021-01-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0027_librarysubset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarysubset',
            name='proposal',
        ),
    ]
