# Generated by Django 3.1.5 on 2021-01-26 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0029_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='proposal',
        ),
        migrations.AddField(
            model_name='proposal',
            name='protein',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='playground.protein'),
        ),
    ]
