# Generated by Django 3.1.5 on 2021-01-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0032_proposal_libraries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='libraries',
            field=models.ManyToManyField(blank=True, to='playground.Library'),
        ),
    ]
