# Generated by Django 3.1.5 on 2021-01-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0034_proposal_subsets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('subsets', models.ManyToManyField(to='playground.LibrarySubset')),
            ],
        ),
    ]
