# Generated by Django 3.1.5 on 2021-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0035_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_collection_visit', models.TextField(blank=True, null=True)),
                ('expr_conc', models.FloatField(blank=True, null=True)),
                ('harvest_status', models.TextField(blank=True, null=True)),
                ('mounting_result', models.TextField(blank=True, null=True)),
                ('mounting_time', models.TextField(blank=True, null=True)),
                ('visit', models.TextField(blank=True, null=True)),
                ('puck', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('mounted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ispyb_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
