# Generated by Django 3.1.5 on 2021-01-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0037_soakdbcompound'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrystalPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('drop_volume', models.FloatField()),
                ('plate_type', models.CharField(max_length=100)),
            ],
        ),
    ]
