# Generated by Django 3.1.5 on 2021-01-26 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0039_crystal'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystal',
            name='crystal_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='playground.crystalplate'),
        ),
        migrations.AddField(
            model_name='crystal',
            name='echo_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crystal',
            name='echo_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crystal',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crystal',
            name='well',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
