# Generated by Django 3.1.5 on 2021-01-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0041_auto_20210126_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('soak_status', models.CharField(blank=True, max_length=64, null=True)),
                ('soak_time', models.IntegerField(blank=True, null=True)),
                ('solv_frac', models.FloatField(blank=True, null=True)),
                ('stock_conc', models.FloatField(blank=True, null=True)),
                ('cryo_frac', models.FloatField(blank=True, null=True)),
                ('cryo_status', models.CharField(blank=True, max_length=64, null=True)),
                ('cryo_stock_frac', models.FloatField(blank=True, null=True)),
                ('cryo_location', models.CharField(blank=True, max_length=4, null=True)),
                ('crystal_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.crystalplate')),
            ],
        ),
    ]
