# Generated by Django 3.1.5 on 2021-01-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0042_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='playground.batch'),
        ),
    ]
