# Generated by Django 3.1.5 on 2021-01-26 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0043_lab_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewell',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='playground.compound'),
        ),
        migrations.AlterField(
            model_name='sourcewell',
            name='library_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='playground.libraryplate'),
        ),
    ]
