# Generated by Django 3.1.5 on 2021-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0044_auto_20210126_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysubset',
            name='compounds',
            field=models.ManyToManyField(to='playground.Compound'),
        ),
    ]
