# Generated by Django 3.1.5 on 2021-01-29 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0045_auto_20210127_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystal',
            name='crystal_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crystals', to='playground.crystalplate'),
        ),
    ]
